[FIXED JENKINS-10641] JDK installation on SSH slaves broken.
[09/28/11 21:44:14] [SSH] Checking java version of /home/gem/workspace/jdk/bin/java
Couldn't figure out the Java version of /home/gem/workspace/jdk/bin/java
bash: /home/gem/workspace/jdk/bin/java: No such file or directory

Linux dogwood 2.6.32-27-generic-pae #49-Ubuntu SMP Thu Dec 2 00:07:52 UTC 2010 i686 GNU/Linux
Installing JDK jdk-6u16-oth-JPR@CDS-CDS_Developer
Downloading JDK from http://download.oracle.com/otn/java/jdk/6u16-b01//jdk-6u16-linux-i586.bin
ERROR: Unexpected error in launching a slave. This is probably a bug in Jenkins.
java.lang.AssertionError: class hudson.plugins.sshslaves.SSHLauncher$DefaultJDKInstaller is missing its descriptor
	at jenkins.model.Jenkins.getDescriptorOrDie(Jenkins.java:1076)
	at hudson.tools.ToolInstaller.getDescriptor(ToolInstaller.java:125)
	at hudson.tools.JDKInstaller.getDescriptor(JDKInstaller.java:587)
	at hudson.tools.JDKInstaller.locate(JDKInstaller.java:359)
	at hudson.plugins.sshslaves.SSHLauncher.attemptToInstallJDK(SSHLauncher.java:385)
	at hudson.plugins.sshslaves.SSHLauncher.resolveJava(SSHLauncher.java:319)
	at hudson.plugins.sshslaves.SSHLauncher.launch(SSHLauncher.java:259)
	at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:199)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:636)
[09/28/11 21:44:18] [SSH] Connection closed.